baseurl = "https://blog.hassaku-labs.com/"
theme = "angels-ladder"
languageCode = "ja"
title = "hassaku's blog"
canonifyurls = true
publishdir = "pages"
disqusShortname = "hassakusblog"
[taxonomies]
tag = "tags"

[params]
  subtitle = "３歩進んで２歩分滑り落ちてくペンギンのメモ"
  github = "https://github.com/hassaku"
  profile = "/images/profile.png"
  copyright = "Written by hassaku"
  analytics = "UA-31136981-6"
