baseurl = "http://hassaku.github.io/blog/"
theme = "angels-ladder"
languageCode = "ja"
title = "hassaku's blog"
canonifyurls = "true"
publishdir = "pages"

[params]
  subtitle = "just note"
  github = "https://github.com/hassaku"
  profile = "/images/profile.png"
  copyright = "Written by hassaku"
