theme = "angels-ladder"
languageCode = "ja"
title = "hassaku's blog"

[Params]
subtitle = "just note"
github = "https://github.com/hassaku"
profile = "/images/profile.png"
copyright = "Written by hassaku"
